"""Generate the sample incident report deliverable (JSON + readable Markdown).

Runs the pipeline, takes the top-N flagged incidents with their narratives, and
writes both a machine-readable JSON and a human-readable Markdown report to
``reports/`` (committed, unlike the gitignored data/output/).

Run:  python -m src.report
"""
from __future__ import annotations

import json

import config
from src.ingestor import load_access_logs, load_user_profiles, merge_logs_with_profiles
from src.baseline import build_all_baselines
from src.detector import score_all_events
from src.suppressor import apply_suppression
from src.llm_narrator import narrate_flagged_incidents

REPORTS_DIR = config.ROOT / "reports"
_DIMS = ["dim1_time", "dim2_action_sensitivity", "dim3_resource", "dim4_stale", "dim5_privilege"]


def build_incident_records(n: int = 25) -> list[dict]:
    """Run the pipeline and return the top-N flagged incidents as structured dicts."""
    profiles = load_user_profiles()
    df = merge_logs_with_profiles(load_access_logs(), profiles)
    baselines = build_all_baselines(df, profiles)
    scored = apply_suppression(score_all_events(df, baselines, write=False))
    flagged = narrate_flagged_incidents(scored, baselines, limit=n, write=False)

    records = []
    for rank, (idx, r) in enumerate(flagged.iterrows(), start=1):
        records.append({
            "rank": rank,
            "incident_id": int(idx),
            "risk_score": int(r["adjusted_risk_score"]),
            "severity": r["adjusted_severity"],
            "user": r[config.COL_USERNAME],
            "role": f"{r[config.COL_JOB_TITLE]}, {r[config.COL_DEPARTMENT]}",
            "privilege": r[config.COL_PRIVILEGE],
            "timestamp": str(r[config.COL_TIMESTAMP]),
            "event": (f"{r[config.COL_ACTION]} on {r[config.COL_RESOURCE]} "
                      f"({r[config.COL_SENSITIVITY]}), {r[config.COL_STATUS]}, "
                      f"{r[config.COL_TIME_CLASS]}"),
            "dimension_scores": {d: int(r[d]) for d in _DIMS},
            "anomaly_signals": [s for s in str(r["anomaly_signals"]).split("; ") if s],
            "confidence": int(r["llm_confidence"]) if r["llm_confidence"] == r["llm_confidence"] else None,
            "narrative_source": r["narrative_source"],
            "narrative": r["llm_narrative"],
            "recommended_actions": [a for a in str(r["llm_recommended_actions"]).split(" | ") if a],
            "suppression": r["suppression_reason"] or None,
        })
    return records


def write_report(n: int = 25) -> None:
    """Write reports/incident_report.{json,md} for the top-N incidents."""
    records = build_incident_records(n)
    REPORTS_DIR.mkdir(exist_ok=True)

    (REPORTS_DIR / "incident_report.json").write_text(
        json.dumps(records, indent=2), encoding="utf-8")

    sev_counts: dict[str, int] = {}
    for r in records:
        sev_counts[r["severity"]] = sev_counts.get(r["severity"], 0) + 1

    lines = [
        "# Sample Incident Report",
        "",
        "_Data Access Audit & Insider Threat Detection (PS-04). Auto-generated by "
        "`python -m src.report`._",
        "",
        f"**{len(records)} highest-risk flagged incidents.** "
        + " | ".join(f"{k}: {v}" for k, v in sorted(sev_counts.items())),
        "",
        "---",
        "",
    ]
    for r in records:
        lines += [
            f"## #{r['rank']} - {r['severity']} - risk {r['risk_score']}/100 - {r['user']}",
            "",
            f"- **User:** {r['user']} ({r['role']}, {r['privilege']})",
            f"- **Event:** {r['event']}",
            f"- **When:** {r['timestamp']}",
            f"- **Dimension scores:** " + ", ".join(
                f"{k.replace('dim', 'D').split('_')[0]}={v}" for k, v in r["dimension_scores"].items()),
            f"- **Signals:** " + "; ".join(r["anomaly_signals"]),
            f"- **Narrative** ({r['narrative_source']}, {r['confidence']}% confidence): {r['narrative']}",
            "- **Recommended actions:**",
        ]
        lines += [f"  {i}. {a}" for i, a in enumerate(r["recommended_actions"], 1)]
        if r["suppression"]:
            lines.append(f"- _Suppression applied:_ {r['suppression']}")
        lines += ["", "---", ""]

    (REPORTS_DIR / "incident_report.md").write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {len(records)} incidents to reports/incident_report.json and .md")


if __name__ == "__main__":
    write_report(25)
